"""Shared fixtures.

Fixtures under ``tests/fixtures/`` are regenerated by
``python scripts/build_fixtures.py``. Their label values are illustrative,
never Human Gold.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from articulm.config import DataConfig, ModelConfig, load_data_config, load_model_config
from articulm.data.dataset import PhonemeSequenceDataset
from articulm.data.schema import Sample, load_samples
from articulm.data.vocab import FeatureVocabulary, build_vocabulary

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"
CONFIG_DIR = REPO_ROOT / "config"


@pytest.fixture(scope="session")
def repo_root() -> Path:
    return REPO_ROOT


@pytest.fixture(scope="session")
def fixture_dir() -> Path:
    return FIXTURE_DIR


@pytest.fixture(scope="session")
def config_dir() -> Path:
    return CONFIG_DIR


@pytest.fixture(scope="session")
def model_config() -> ModelConfig:
    return load_model_config(CONFIG_DIR / "model_v1_50m.yaml")


@pytest.fixture(scope="session")
def data_config() -> DataConfig:
    return load_data_config(CONFIG_DIR / "data_v1.yaml")


@pytest.fixture(scope="session")
def fixture_paths() -> dict[str, Path]:
    return {
        "zh": FIXTURE_DIR / "sample_zh.jsonl",
        "en": FIXTURE_DIR / "sample_en.jsonl",
        "mixed": FIXTURE_DIR / "sample_mixed.jsonl",
    }


@pytest.fixture(scope="session")
def raw_fixture_records(fixture_paths: dict[str, Path]) -> dict[str, list[dict]]:
    records: dict[str, list[dict]] = {}
    for key, path in fixture_paths.items():
        with path.open("r", encoding="utf-8") as fh:
            records[key] = [json.loads(line) for line in fh if line.strip()]
    return records


@pytest.fixture(scope="session")
def all_samples(fixture_paths: dict[str, Path], data_config: DataConfig) -> list[Sample]:
    samples: list[Sample] = []
    for path in fixture_paths.values():
        samples.extend(load_samples(path, data_config))
    return samples


@pytest.fixture(scope="session")
def vocab(all_samples: list[Sample], data_config: DataConfig) -> FeatureVocabulary:
    return build_vocabulary(all_samples, data_config)


@pytest.fixture
def dataset(all_samples: list[Sample], vocab: FeatureVocabulary) -> PhonemeSequenceDataset:
    return PhonemeSequenceDataset(all_samples, vocab)


@pytest.fixture(scope="session")
def tiny_model_config(model_config: ModelConfig) -> ModelConfig:
    """A 2-layer, narrow model for fast tests.

    Dimensions stay internally consistent so config validation still applies;
    the 10x640 baseline itself is asserted separately in test_config.py.
    """
    import dataclasses

    from articulm.config import (
        ArticulatoryEmbeddingDims,
        EmbeddingDims,
        InputConfig,
        StrengthHeadConfig,
        TransformerConfig,
    )

    articulatory = ArticulatoryEmbeddingDims(
        type=2, height=2, backness=2, rounded=1, place=3, manner=3, voiced=1, aspirated=1
    )
    embedding_dims = EmbeddingDims(
        phoneme=16,
        language=2,
        surface_tone=4,
        stress=2,
        syllable_role=4,
        articulatory=articulatory,
        boundary=5,
    )
    return dataclasses.replace(
        model_config,
        input=InputConfig(
            max_seq_len=128,
            embedding_dims=embedding_dims,
            fused_input_dim=embedding_dims.total,
        ),
        fusion=dataclasses.replace(model_config.fusion, output_dim=64),
        transformer=TransformerConfig(
            hidden_size=64, num_layers=2, num_heads=4, head_dim=16, ffn_size=128
        ),
        viseme_head=dataclasses.replace(model_config.viseme_head, hidden_size=32),
        strength_head=StrengthHeadConfig(
            input_dim=64 + model_config.viseme_embedding.dim, hidden_dims=(32, 16)
        ),
    )
